# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.09.040955'

RELEASE_GIT_HEAD = 'aa863ddab9b1d104678e9cf39bb76f5b14fca660'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Haoqi7/yt-dlp'

ORIGIN = 'Haoqi7/yt-dlp'

_pkg_version = '2025.06.09.040955'
