# Autogenerated by devscripts/update-version.py

__version__ = '2025.07.22.103404'

RELEASE_GIT_HEAD = '035b1ece8f382358f5503bf5011ca098f6c9eaf9'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Haoqi7/yt-dlp'

ORIGIN = 'Haoqi7/yt-dlp'

_pkg_version = '2025.07.22.103404'
